name: mintart
description: "MintArt is an image generation platform built with Flutter, where users can generate unique images based on their token balance. Upon signing up, users receive a limited number of free tokens to get started. Tokens are required for each image generation request, with the option to purchase additional tokens through a payment gateway integration. MintArt ensures a secure and seamless user experience by incorporating backend validation for token management, a straightforward purchase flow, and controlled access to image downloads. Key features include token-based access, easy image download, and responsive UI updates for token balance."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_offline: ^3.0.1
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  rive: ^0.13.4
  flutter_dotenv: ^5.0.2
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/svgs/